# -*- coding: utf-8 -*-
"""Run_descriptive

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yC4NOLTZ9hph9-nzi6qHh3CwfDQ_nDlV
"""

"""
Ejecutable local (Semana 1 - Descriptivo)

Uso:
    python -m scripts.run_descriptive
"""

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from src.descriptive import numeric_summary, correlation_matrix
from src.io import write_csv


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "processed" / "cancer_mama_piii_2023_clean.csv"
OUT_SUMMARY = ROOT / "data" / "processed" / "numeric_summary.csv"
OUT_CORR = ROOT / "data" / "processed" / "correlation_matrix.csv"


def main() -> None:
    df = pd.read_csv(DATA)

    summary = numeric_summary(df)
    corr = correlation_matrix(df)

    OUT_SUMMARY.parent.mkdir(parents=True, exist_ok=True)

    write_csv(summary, str(OUT_SUMMARY))
    write_csv(corr, str(OUT_CORR))

    # Graficar correlación
    plt.figure(figsize=(10,8))
    sns.heatmap(corr, cmap="coolwarm", center=0)
    plt.title("Matriz de Correlación")
    plt.savefig(ROOT / "data" / "processed" / "correlation_heatmap.png")

    print("Descriptivo generado correctamente.")


if __name__ == "__main__":
    main()